package onight.act.ordbgens.act.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="T_ACT_INTEREST")
@AllArgsConstructor
@NoArgsConstructor
public class TActInterest extends TActInterestKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.INTEREST_DATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String interestDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String fundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.ACT_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String actNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.INTEREST_TYPE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String interestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.INTEREST_AMOUNT
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private BigDecimal interestAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.GMT_CREATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.GMT_MODIFY
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.TRADE_DATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.RATE_VALUE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private BigDecimal rateValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_INTEREST.UNIT_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String unitNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.INTEREST_DATE
     *
     * @return the value of T_ACT_INTEREST.INTEREST_DATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getInterestDate() {
        return interestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.INTEREST_DATE
     *
     * @param interestDate the value for T_ACT_INTEREST.INTEREST_DATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setInterestDate(String interestDate) {
        this.interestDate = interestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.FUND_NO
     *
     * @return the value of T_ACT_INTEREST.FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getFundNo() {
        return fundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.FUND_NO
     *
     * @param fundNo the value for T_ACT_INTEREST.FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setFundNo(String fundNo) {
        this.fundNo = fundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.ACT_NO
     *
     * @return the value of T_ACT_INTEREST.ACT_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getActNo() {
        return actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.ACT_NO
     *
     * @param actNo the value for T_ACT_INTEREST.ACT_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setActNo(String actNo) {
        this.actNo = actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.INTEREST_TYPE
     *
     * @return the value of T_ACT_INTEREST.INTEREST_TYPE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getInterestType() {
        return interestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.INTEREST_TYPE
     *
     * @param interestType the value for T_ACT_INTEREST.INTEREST_TYPE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setInterestType(String interestType) {
        this.interestType = interestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.INTEREST_AMOUNT
     *
     * @return the value of T_ACT_INTEREST.INTEREST_AMOUNT
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public BigDecimal getInterestAmount() {
        return interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.INTEREST_AMOUNT
     *
     * @param interestAmount the value for T_ACT_INTEREST.INTEREST_AMOUNT
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setInterestAmount(BigDecimal interestAmount) {
        this.interestAmount = interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.GMT_CREATE
     *
     * @return the value of T_ACT_INTEREST.GMT_CREATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.GMT_CREATE
     *
     * @param gmtCreate the value for T_ACT_INTEREST.GMT_CREATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.GMT_MODIFY
     *
     * @return the value of T_ACT_INTEREST.GMT_MODIFY
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.GMT_MODIFY
     *
     * @param gmtModify the value for T_ACT_INTEREST.GMT_MODIFY
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.TRADE_DATE
     *
     * @return the value of T_ACT_INTEREST.TRADE_DATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.TRADE_DATE
     *
     * @param tradeDate the value for T_ACT_INTEREST.TRADE_DATE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.RATE_VALUE
     *
     * @return the value of T_ACT_INTEREST.RATE_VALUE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public BigDecimal getRateValue() {
        return rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.RATE_VALUE
     *
     * @param rateValue the value for T_ACT_INTEREST.RATE_VALUE
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setRateValue(BigDecimal rateValue) {
        this.rateValue = rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_INTEREST.UNIT_NO
     *
     * @return the value of T_ACT_INTEREST.UNIT_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getUnitNo() {
        return unitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_INTEREST.UNIT_NO
     *
     * @param unitNo the value for T_ACT_INTEREST.UNIT_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setUnitNo(String unitNo) {
        this.unitNo = unitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TActInterest other = (TActInterest) that;
        return (this.getInstLogid() == null ? other.getInstLogid() == null : this.getInstLogid().equals(other.getInstLogid()))
            && (this.getInterestDate() == null ? other.getInterestDate() == null : this.getInterestDate().equals(other.getInterestDate()))
            && (this.getFundNo() == null ? other.getFundNo() == null : this.getFundNo().equals(other.getFundNo()))
            && (this.getActNo() == null ? other.getActNo() == null : this.getActNo().equals(other.getActNo()))
            && (this.getInterestType() == null ? other.getInterestType() == null : this.getInterestType().equals(other.getInterestType()))
            && (this.getInterestAmount() == null ? other.getInterestAmount() == null : this.getInterestAmount().equals(other.getInterestAmount()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()))
            && (this.getTradeDate() == null ? other.getTradeDate() == null : this.getTradeDate().equals(other.getTradeDate()))
            && (this.getRateValue() == null ? other.getRateValue() == null : this.getRateValue().equals(other.getRateValue()))
            && (this.getUnitNo() == null ? other.getUnitNo() == null : this.getUnitNo().equals(other.getUnitNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInstLogid() == null) ? 0 : getInstLogid().hashCode());
        result = prime * result + ((getInterestDate() == null) ? 0 : getInterestDate().hashCode());
        result = prime * result + ((getFundNo() == null) ? 0 : getFundNo().hashCode());
        result = prime * result + ((getActNo() == null) ? 0 : getActNo().hashCode());
        result = prime * result + ((getInterestType() == null) ? 0 : getInterestType().hashCode());
        result = prime * result + ((getInterestAmount() == null) ? 0 : getInterestAmount().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        result = prime * result + ((getTradeDate() == null) ? 0 : getTradeDate().hashCode());
        result = prime * result + ((getRateValue() == null) ? 0 : getRateValue().hashCode());
        result = prime * result + ((getUnitNo() == null) ? 0 : getUnitNo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", interestDate=").append(interestDate);
        sb.append(", fundNo=").append(fundNo);
        sb.append(", actNo=").append(actNo);
        sb.append(", interestType=").append(interestType);
        sb.append(", interestAmount=").append(interestAmount);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", tradeDate=").append(tradeDate);
        sb.append(", rateValue=").append(rateValue);
        sb.append(", unitNo=").append(unitNo);
        sb.append("]");
        return sb.toString();
    }
}