package onight.act.ordbgens.act.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class TActInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public TActInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActNoIsNull() {
            addCriterion("ACT_NO is null");
            return (Criteria) this;
        }

        public Criteria andActNoIsNotNull() {
            addCriterion("ACT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andActNoEqualTo(String value) {
            addCriterion("ACT_NO =", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotEqualTo(String value) {
            addCriterion("ACT_NO <>", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThan(String value) {
            addCriterion("ACT_NO >", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_NO >=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThan(String value) {
            addCriterion("ACT_NO <", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThanOrEqualTo(String value) {
            addCriterion("ACT_NO <=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLike(String value) {
            addCriterion("ACT_NO like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotLike(String value) {
            addCriterion("ACT_NO not like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoIn(List<String> values) {
            addCriterion("ACT_NO in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotIn(List<String> values) {
            addCriterion("ACT_NO not in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoBetween(String value1, String value2) {
            addCriterion("ACT_NO between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotBetween(String value1, String value2) {
            addCriterion("ACT_NO not between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNameIsNull() {
            addCriterion("ACT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andActNameIsNotNull() {
            addCriterion("ACT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andActNameEqualTo(String value) {
            addCriterion("ACT_NAME =", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameNotEqualTo(String value) {
            addCriterion("ACT_NAME <>", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameGreaterThan(String value) {
            addCriterion("ACT_NAME >", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_NAME >=", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameLessThan(String value) {
            addCriterion("ACT_NAME <", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameLessThanOrEqualTo(String value) {
            addCriterion("ACT_NAME <=", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameLike(String value) {
            addCriterion("ACT_NAME like", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameNotLike(String value) {
            addCriterion("ACT_NAME not like", value, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameIn(List<String> values) {
            addCriterion("ACT_NAME in", values, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameNotIn(List<String> values) {
            addCriterion("ACT_NAME not in", values, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameBetween(String value1, String value2) {
            addCriterion("ACT_NAME between", value1, value2, "actName");
            return (Criteria) this;
        }

        public Criteria andActNameNotBetween(String value1, String value2) {
            addCriterion("ACT_NAME not between", value1, value2, "actName");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("CUST_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("CUST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(String value) {
            addCriterion("CUST_ID =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(String value) {
            addCriterion("CUST_ID <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(String value) {
            addCriterion("CUST_ID >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_ID >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(String value) {
            addCriterion("CUST_ID <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(String value) {
            addCriterion("CUST_ID <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLike(String value) {
            addCriterion("CUST_ID like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotLike(String value) {
            addCriterion("CUST_ID not like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<String> values) {
            addCriterion("CUST_ID in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<String> values) {
            addCriterion("CUST_ID not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(String value1, String value2) {
            addCriterion("CUST_ID between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(String value1, String value2) {
            addCriterion("CUST_ID not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andMchntIdIsNull() {
            addCriterion("MCHNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMchntIdIsNotNull() {
            addCriterion("MCHNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMchntIdEqualTo(String value) {
            addCriterion("MCHNT_ID =", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotEqualTo(String value) {
            addCriterion("MCHNT_ID <>", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdGreaterThan(String value) {
            addCriterion("MCHNT_ID >", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdGreaterThanOrEqualTo(String value) {
            addCriterion("MCHNT_ID >=", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLessThan(String value) {
            addCriterion("MCHNT_ID <", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLessThanOrEqualTo(String value) {
            addCriterion("MCHNT_ID <=", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLike(String value) {
            addCriterion("MCHNT_ID like", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotLike(String value) {
            addCriterion("MCHNT_ID not like", value, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdIn(List<String> values) {
            addCriterion("MCHNT_ID in", values, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotIn(List<String> values) {
            addCriterion("MCHNT_ID not in", values, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdBetween(String value1, String value2) {
            addCriterion("MCHNT_ID between", value1, value2, "mchntId");
            return (Criteria) this;
        }

        public Criteria andMchntIdNotBetween(String value1, String value2) {
            addCriterion("MCHNT_ID not between", value1, value2, "mchntId");
            return (Criteria) this;
        }

        public Criteria andActTypeIsNull() {
            addCriterion("ACT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andActTypeIsNotNull() {
            addCriterion("ACT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andActTypeEqualTo(String value) {
            addCriterion("ACT_TYPE =", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeNotEqualTo(String value) {
            addCriterion("ACT_TYPE <>", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeGreaterThan(String value) {
            addCriterion("ACT_TYPE >", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_TYPE >=", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeLessThan(String value) {
            addCriterion("ACT_TYPE <", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeLessThanOrEqualTo(String value) {
            addCriterion("ACT_TYPE <=", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeLike(String value) {
            addCriterion("ACT_TYPE like", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeNotLike(String value) {
            addCriterion("ACT_TYPE not like", value, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeIn(List<String> values) {
            addCriterion("ACT_TYPE in", values, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeNotIn(List<String> values) {
            addCriterion("ACT_TYPE not in", values, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeBetween(String value1, String value2) {
            addCriterion("ACT_TYPE between", value1, value2, "actType");
            return (Criteria) this;
        }

        public Criteria andActTypeNotBetween(String value1, String value2) {
            addCriterion("ACT_TYPE not between", value1, value2, "actType");
            return (Criteria) this;
        }

        public Criteria andMnySmbIsNull() {
            addCriterion("MNY_SMB is null");
            return (Criteria) this;
        }

        public Criteria andMnySmbIsNotNull() {
            addCriterion("MNY_SMB is not null");
            return (Criteria) this;
        }

        public Criteria andMnySmbEqualTo(String value) {
            addCriterion("MNY_SMB =", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbNotEqualTo(String value) {
            addCriterion("MNY_SMB <>", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbGreaterThan(String value) {
            addCriterion("MNY_SMB >", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbGreaterThanOrEqualTo(String value) {
            addCriterion("MNY_SMB >=", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbLessThan(String value) {
            addCriterion("MNY_SMB <", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbLessThanOrEqualTo(String value) {
            addCriterion("MNY_SMB <=", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbLike(String value) {
            addCriterion("MNY_SMB like", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbNotLike(String value) {
            addCriterion("MNY_SMB not like", value, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbIn(List<String> values) {
            addCriterion("MNY_SMB in", values, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbNotIn(List<String> values) {
            addCriterion("MNY_SMB not in", values, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbBetween(String value1, String value2) {
            addCriterion("MNY_SMB between", value1, value2, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andMnySmbNotBetween(String value1, String value2) {
            addCriterion("MNY_SMB not between", value1, value2, "mnySmb");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("CHANNEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("CHANNEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("CHANNEL_ID =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("CHANNEL_ID <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("CHANNEL_ID >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("CHANNEL_ID <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("CHANNEL_ID like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("CHANNEL_ID not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("CHANNEL_ID in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("CHANNEL_ID not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andCatalogIsNull() {
            addCriterion("CATALOG is null");
            return (Criteria) this;
        }

        public Criteria andCatalogIsNotNull() {
            addCriterion("CATALOG is not null");
            return (Criteria) this;
        }

        public Criteria andCatalogEqualTo(String value) {
            addCriterion("CATALOG =", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotEqualTo(String value) {
            addCriterion("CATALOG <>", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogGreaterThan(String value) {
            addCriterion("CATALOG >", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogGreaterThanOrEqualTo(String value) {
            addCriterion("CATALOG >=", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogLessThan(String value) {
            addCriterion("CATALOG <", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogLessThanOrEqualTo(String value) {
            addCriterion("CATALOG <=", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogLike(String value) {
            addCriterion("CATALOG like", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotLike(String value) {
            addCriterion("CATALOG not like", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogIn(List<String> values) {
            addCriterion("CATALOG in", values, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotIn(List<String> values) {
            addCriterion("CATALOG not in", values, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogBetween(String value1, String value2) {
            addCriterion("CATALOG between", value1, value2, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotBetween(String value1, String value2) {
            addCriterion("CATALOG not between", value1, value2, "catalog");
            return (Criteria) this;
        }

        public Criteria andActYinitBalIsNull() {
            addCriterion("ACT_YINIT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andActYinitBalIsNotNull() {
            addCriterion("ACT_YINIT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andActYinitBalEqualTo(BigDecimal value) {
            addCriterion("ACT_YINIT_BAL =", value, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalNotEqualTo(BigDecimal value) {
            addCriterion("ACT_YINIT_BAL <>", value, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalGreaterThan(BigDecimal value) {
            addCriterion("ACT_YINIT_BAL >", value, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_YINIT_BAL >=", value, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalLessThan(BigDecimal value) {
            addCriterion("ACT_YINIT_BAL <", value, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_YINIT_BAL <=", value, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalIn(List<BigDecimal> values) {
            addCriterion("ACT_YINIT_BAL in", values, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalNotIn(List<BigDecimal> values) {
            addCriterion("ACT_YINIT_BAL not in", values, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_YINIT_BAL between", value1, value2, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActYinitBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_YINIT_BAL not between", value1, value2, "actYinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalIsNull() {
            addCriterion("ACT_DINIT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andActDinitBalIsNotNull() {
            addCriterion("ACT_DINIT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andActDinitBalEqualTo(BigDecimal value) {
            addCriterion("ACT_DINIT_BAL =", value, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalNotEqualTo(BigDecimal value) {
            addCriterion("ACT_DINIT_BAL <>", value, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalGreaterThan(BigDecimal value) {
            addCriterion("ACT_DINIT_BAL >", value, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_DINIT_BAL >=", value, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalLessThan(BigDecimal value) {
            addCriterion("ACT_DINIT_BAL <", value, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_DINIT_BAL <=", value, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalIn(List<BigDecimal> values) {
            addCriterion("ACT_DINIT_BAL in", values, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalNotIn(List<BigDecimal> values) {
            addCriterion("ACT_DINIT_BAL not in", values, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_DINIT_BAL between", value1, value2, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActDinitBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_DINIT_BAL not between", value1, value2, "actDinitBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalIsNull() {
            addCriterion("ACT_CUR_BAL is null");
            return (Criteria) this;
        }

        public Criteria andActCurBalIsNotNull() {
            addCriterion("ACT_CUR_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andActCurBalEqualTo(BigDecimal value) {
            addCriterion("ACT_CUR_BAL =", value, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalNotEqualTo(BigDecimal value) {
            addCriterion("ACT_CUR_BAL <>", value, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalGreaterThan(BigDecimal value) {
            addCriterion("ACT_CUR_BAL >", value, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_CUR_BAL >=", value, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalLessThan(BigDecimal value) {
            addCriterion("ACT_CUR_BAL <", value, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_CUR_BAL <=", value, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalIn(List<BigDecimal> values) {
            addCriterion("ACT_CUR_BAL in", values, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalNotIn(List<BigDecimal> values) {
            addCriterion("ACT_CUR_BAL not in", values, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_CUR_BAL between", value1, value2, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActCurBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_CUR_BAL not between", value1, value2, "actCurBal");
            return (Criteria) this;
        }

        public Criteria andActStatIsNull() {
            addCriterion("ACT_STAT is null");
            return (Criteria) this;
        }

        public Criteria andActStatIsNotNull() {
            addCriterion("ACT_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andActStatEqualTo(BigDecimal value) {
            addCriterion("ACT_STAT =", value, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatNotEqualTo(BigDecimal value) {
            addCriterion("ACT_STAT <>", value, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatGreaterThan(BigDecimal value) {
            addCriterion("ACT_STAT >", value, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_STAT >=", value, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatLessThan(BigDecimal value) {
            addCriterion("ACT_STAT <", value, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_STAT <=", value, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatIn(List<BigDecimal> values) {
            addCriterion("ACT_STAT in", values, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatNotIn(List<BigDecimal> values) {
            addCriterion("ACT_STAT not in", values, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_STAT between", value1, value2, "actStat");
            return (Criteria) this;
        }

        public Criteria andActStatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_STAT not between", value1, value2, "actStat");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtIsNull() {
            addCriterion("ACT_MAXOD_AMT is null");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtIsNotNull() {
            addCriterion("ACT_MAXOD_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtEqualTo(BigDecimal value) {
            addCriterion("ACT_MAXOD_AMT =", value, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtNotEqualTo(BigDecimal value) {
            addCriterion("ACT_MAXOD_AMT <>", value, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtGreaterThan(BigDecimal value) {
            addCriterion("ACT_MAXOD_AMT >", value, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_MAXOD_AMT >=", value, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtLessThan(BigDecimal value) {
            addCriterion("ACT_MAXOD_AMT <", value, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_MAXOD_AMT <=", value, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtIn(List<BigDecimal> values) {
            addCriterion("ACT_MAXOD_AMT in", values, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtNotIn(List<BigDecimal> values) {
            addCriterion("ACT_MAXOD_AMT not in", values, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_MAXOD_AMT between", value1, value2, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActMaxodAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_MAXOD_AMT not between", value1, value2, "actMaxodAmt");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalIsNull() {
            addCriterion("ACT_CTRL_BAL is null");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalIsNotNull() {
            addCriterion("ACT_CTRL_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalEqualTo(BigDecimal value) {
            addCriterion("ACT_CTRL_BAL =", value, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalNotEqualTo(BigDecimal value) {
            addCriterion("ACT_CTRL_BAL <>", value, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalGreaterThan(BigDecimal value) {
            addCriterion("ACT_CTRL_BAL >", value, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_CTRL_BAL >=", value, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalLessThan(BigDecimal value) {
            addCriterion("ACT_CTRL_BAL <", value, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_CTRL_BAL <=", value, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalIn(List<BigDecimal> values) {
            addCriterion("ACT_CTRL_BAL in", values, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalNotIn(List<BigDecimal> values) {
            addCriterion("ACT_CTRL_BAL not in", values, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_CTRL_BAL between", value1, value2, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActCtrlBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_CTRL_BAL not between", value1, value2, "actCtrlBal");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagIsNull() {
            addCriterion("ACT_BAL_WARN_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagIsNotNull() {
            addCriterion("ACT_BAL_WARN_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagEqualTo(String value) {
            addCriterion("ACT_BAL_WARN_FLAG =", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagNotEqualTo(String value) {
            addCriterion("ACT_BAL_WARN_FLAG <>", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagGreaterThan(String value) {
            addCriterion("ACT_BAL_WARN_FLAG >", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_BAL_WARN_FLAG >=", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagLessThan(String value) {
            addCriterion("ACT_BAL_WARN_FLAG <", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagLessThanOrEqualTo(String value) {
            addCriterion("ACT_BAL_WARN_FLAG <=", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagLike(String value) {
            addCriterion("ACT_BAL_WARN_FLAG like", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagNotLike(String value) {
            addCriterion("ACT_BAL_WARN_FLAG not like", value, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagIn(List<String> values) {
            addCriterion("ACT_BAL_WARN_FLAG in", values, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagNotIn(List<String> values) {
            addCriterion("ACT_BAL_WARN_FLAG not in", values, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagBetween(String value1, String value2) {
            addCriterion("ACT_BAL_WARN_FLAG between", value1, value2, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagNotBetween(String value1, String value2) {
            addCriterion("ACT_BAL_WARN_FLAG not between", value1, value2, "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("MODIFY_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("MODIFY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(String value) {
            addCriterion("MODIFY_ID =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(String value) {
            addCriterion("MODIFY_ID <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(String value) {
            addCriterion("MODIFY_ID >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_ID >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(String value) {
            addCriterion("MODIFY_ID <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_ID <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLike(String value) {
            addCriterion("MODIFY_ID like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotLike(String value) {
            addCriterion("MODIFY_ID not like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<String> values) {
            addCriterion("MODIFY_ID in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<String> values) {
            addCriterion("MODIFY_ID not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(String value1, String value2) {
            addCriterion("MODIFY_ID between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(String value1, String value2) {
            addCriterion("MODIFY_ID not between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andActNoLikeInsensitive(String value) {
            addCriterion("upper(ACT_NO) like", value.toUpperCase(), "actNo");
            return (Criteria) this;
        }

        public Criteria andActNameLikeInsensitive(String value) {
            addCriterion("upper(ACT_NAME) like", value.toUpperCase(), "actName");
            return (Criteria) this;
        }

        public Criteria andCustIdLikeInsensitive(String value) {
            addCriterion("upper(CUST_ID) like", value.toUpperCase(), "custId");
            return (Criteria) this;
        }

        public Criteria andMchntIdLikeInsensitive(String value) {
            addCriterion("upper(MCHNT_ID) like", value.toUpperCase(), "mchntId");
            return (Criteria) this;
        }

        public Criteria andActTypeLikeInsensitive(String value) {
            addCriterion("upper(ACT_TYPE) like", value.toUpperCase(), "actType");
            return (Criteria) this;
        }

        public Criteria andMnySmbLikeInsensitive(String value) {
            addCriterion("upper(MNY_SMB) like", value.toUpperCase(), "mnySmb");
            return (Criteria) this;
        }

        public Criteria andChannelIdLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_ID) like", value.toUpperCase(), "channelId");
            return (Criteria) this;
        }

        public Criteria andCatalogLikeInsensitive(String value) {
            addCriterion("upper(CATALOG) like", value.toUpperCase(), "catalog");
            return (Criteria) this;
        }

        public Criteria andActBalWarnFlagLikeInsensitive(String value) {
            addCriterion("upper(ACT_BAL_WARN_FLAG) like", value.toUpperCase(), "actBalWarnFlag");
            return (Criteria) this;
        }

        public Criteria andModifyIdLikeInsensitive(String value) {
            addCriterion("upper(MODIFY_ID) like", value.toUpperCase(), "modifyId");
            return (Criteria) this;
        }

        public Criteria andMemoLikeInsensitive(String value) {
            addCriterion("upper(MEMO) like", value.toUpperCase(), "memo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 19 22:41:13 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_INFO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}