package onight.act.ordbgens.act.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class TActTransLogsHisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public TActTransLogsHisExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogUuidIsNull() {
            addCriterion("LOG_UUID is null");
            return (Criteria) this;
        }

        public Criteria andLogUuidIsNotNull() {
            addCriterion("LOG_UUID is not null");
            return (Criteria) this;
        }

        public Criteria andLogUuidEqualTo(String value) {
            addCriterion("LOG_UUID =", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotEqualTo(String value) {
            addCriterion("LOG_UUID <>", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidGreaterThan(String value) {
            addCriterion("LOG_UUID >", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_UUID >=", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLessThan(String value) {
            addCriterion("LOG_UUID <", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLessThanOrEqualTo(String value) {
            addCriterion("LOG_UUID <=", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLike(String value) {
            addCriterion("LOG_UUID like", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotLike(String value) {
            addCriterion("LOG_UUID not like", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidIn(List<String> values) {
            addCriterion("LOG_UUID in", values, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotIn(List<String> values) {
            addCriterion("LOG_UUID not in", values, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidBetween(String value1, String value2) {
            addCriterion("LOG_UUID between", value1, value2, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotBetween(String value1, String value2) {
            addCriterion("LOG_UUID not between", value1, value2, "logUuid");
            return (Criteria) this;
        }

        public Criteria andSettDateIsNull() {
            addCriterion("SETT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSettDateIsNotNull() {
            addCriterion("SETT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSettDateEqualTo(String value) {
            addCriterion("SETT_DATE =", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotEqualTo(String value) {
            addCriterion("SETT_DATE <>", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateGreaterThan(String value) {
            addCriterion("SETT_DATE >", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateGreaterThanOrEqualTo(String value) {
            addCriterion("SETT_DATE >=", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateLessThan(String value) {
            addCriterion("SETT_DATE <", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateLessThanOrEqualTo(String value) {
            addCriterion("SETT_DATE <=", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateLike(String value) {
            addCriterion("SETT_DATE like", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotLike(String value) {
            addCriterion("SETT_DATE not like", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateIn(List<String> values) {
            addCriterion("SETT_DATE in", values, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotIn(List<String> values) {
            addCriterion("SETT_DATE not in", values, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateBetween(String value1, String value2) {
            addCriterion("SETT_DATE between", value1, value2, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotBetween(String value1, String value2) {
            addCriterion("SETT_DATE not between", value1, value2, "settDate");
            return (Criteria) this;
        }

        public Criteria andConsDateIsNull() {
            addCriterion("CONS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andConsDateIsNotNull() {
            addCriterion("CONS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andConsDateEqualTo(String value) {
            addCriterion("CONS_DATE =", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotEqualTo(String value) {
            addCriterion("CONS_DATE <>", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateGreaterThan(String value) {
            addCriterion("CONS_DATE >", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateGreaterThanOrEqualTo(String value) {
            addCriterion("CONS_DATE >=", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLessThan(String value) {
            addCriterion("CONS_DATE <", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLessThanOrEqualTo(String value) {
            addCriterion("CONS_DATE <=", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLike(String value) {
            addCriterion("CONS_DATE like", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotLike(String value) {
            addCriterion("CONS_DATE not like", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateIn(List<String> values) {
            addCriterion("CONS_DATE in", values, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotIn(List<String> values) {
            addCriterion("CONS_DATE not in", values, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateBetween(String value1, String value2) {
            addCriterion("CONS_DATE between", value1, value2, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotBetween(String value1, String value2) {
            addCriterion("CONS_DATE not between", value1, value2, "consDate");
            return (Criteria) this;
        }

        public Criteria andTxSnoIsNull() {
            addCriterion("TX_SNO is null");
            return (Criteria) this;
        }

        public Criteria andTxSnoIsNotNull() {
            addCriterion("TX_SNO is not null");
            return (Criteria) this;
        }

        public Criteria andTxSnoEqualTo(String value) {
            addCriterion("TX_SNO =", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotEqualTo(String value) {
            addCriterion("TX_SNO <>", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoGreaterThan(String value) {
            addCriterion("TX_SNO >", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoGreaterThanOrEqualTo(String value) {
            addCriterion("TX_SNO >=", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoLessThan(String value) {
            addCriterion("TX_SNO <", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoLessThanOrEqualTo(String value) {
            addCriterion("TX_SNO <=", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoLike(String value) {
            addCriterion("TX_SNO like", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotLike(String value) {
            addCriterion("TX_SNO not like", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoIn(List<String> values) {
            addCriterion("TX_SNO in", values, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotIn(List<String> values) {
            addCriterion("TX_SNO not in", values, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoBetween(String value1, String value2) {
            addCriterion("TX_SNO between", value1, value2, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotBetween(String value1, String value2) {
            addCriterion("TX_SNO not between", value1, value2, "txSno");
            return (Criteria) this;
        }

        public Criteria andTransCodeIsNull() {
            addCriterion("TRANS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTransCodeIsNotNull() {
            addCriterion("TRANS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTransCodeEqualTo(String value) {
            addCriterion("TRANS_CODE =", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotEqualTo(String value) {
            addCriterion("TRANS_CODE <>", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeGreaterThan(String value) {
            addCriterion("TRANS_CODE >", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_CODE >=", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLessThan(String value) {
            addCriterion("TRANS_CODE <", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLessThanOrEqualTo(String value) {
            addCriterion("TRANS_CODE <=", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLike(String value) {
            addCriterion("TRANS_CODE like", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotLike(String value) {
            addCriterion("TRANS_CODE not like", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeIn(List<String> values) {
            addCriterion("TRANS_CODE in", values, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotIn(List<String> values) {
            addCriterion("TRANS_CODE not in", values, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeBetween(String value1, String value2) {
            addCriterion("TRANS_CODE between", value1, value2, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotBetween(String value1, String value2) {
            addCriterion("TRANS_CODE not between", value1, value2, "transCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeIsNull() {
            addCriterion("SUB_TRANS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeIsNotNull() {
            addCriterion("SUB_TRANS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeEqualTo(String value) {
            addCriterion("SUB_TRANS_CODE =", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeNotEqualTo(String value) {
            addCriterion("SUB_TRANS_CODE <>", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeGreaterThan(String value) {
            addCriterion("SUB_TRANS_CODE >", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_TRANS_CODE >=", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeLessThan(String value) {
            addCriterion("SUB_TRANS_CODE <", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeLessThanOrEqualTo(String value) {
            addCriterion("SUB_TRANS_CODE <=", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeLike(String value) {
            addCriterion("SUB_TRANS_CODE like", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeNotLike(String value) {
            addCriterion("SUB_TRANS_CODE not like", value, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeIn(List<String> values) {
            addCriterion("SUB_TRANS_CODE in", values, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeNotIn(List<String> values) {
            addCriterion("SUB_TRANS_CODE not in", values, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeBetween(String value1, String value2) {
            addCriterion("SUB_TRANS_CODE between", value1, value2, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeNotBetween(String value1, String value2) {
            addCriterion("SUB_TRANS_CODE not between", value1, value2, "subTransCode");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("BIZ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("BIZ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(String value) {
            addCriterion("BIZ_TYPE =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(String value) {
            addCriterion("BIZ_TYPE <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(String value) {
            addCriterion("BIZ_TYPE >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(String value) {
            addCriterion("BIZ_TYPE <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLike(String value) {
            addCriterion("BIZ_TYPE like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotLike(String value) {
            addCriterion("BIZ_TYPE not like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<String> values) {
            addCriterion("BIZ_TYPE in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<String> values) {
            addCriterion("BIZ_TYPE not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE not between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeIsNull() {
            addCriterion("BIZ_DTL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeIsNotNull() {
            addCriterion("BIZ_DTL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE =", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE <>", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeGreaterThan(String value) {
            addCriterion("BIZ_DTL_TYPE >", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE >=", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLessThan(String value) {
            addCriterion("BIZ_DTL_TYPE <", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLessThanOrEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE <=", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLike(String value) {
            addCriterion("BIZ_DTL_TYPE like", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotLike(String value) {
            addCriterion("BIZ_DTL_TYPE not like", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeIn(List<String> values) {
            addCriterion("BIZ_DTL_TYPE in", values, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotIn(List<String> values) {
            addCriterion("BIZ_DTL_TYPE not in", values, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeBetween(String value1, String value2) {
            addCriterion("BIZ_DTL_TYPE between", value1, value2, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotBetween(String value1, String value2) {
            addCriterion("BIZ_DTL_TYPE not between", value1, value2, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andFromFundNoIsNull() {
            addCriterion("FROM_FUND_NO is null");
            return (Criteria) this;
        }

        public Criteria andFromFundNoIsNotNull() {
            addCriterion("FROM_FUND_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFromFundNoEqualTo(String value) {
            addCriterion("FROM_FUND_NO =", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoNotEqualTo(String value) {
            addCriterion("FROM_FUND_NO <>", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoGreaterThan(String value) {
            addCriterion("FROM_FUND_NO >", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoGreaterThanOrEqualTo(String value) {
            addCriterion("FROM_FUND_NO >=", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoLessThan(String value) {
            addCriterion("FROM_FUND_NO <", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoLessThanOrEqualTo(String value) {
            addCriterion("FROM_FUND_NO <=", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoLike(String value) {
            addCriterion("FROM_FUND_NO like", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoNotLike(String value) {
            addCriterion("FROM_FUND_NO not like", value, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoIn(List<String> values) {
            addCriterion("FROM_FUND_NO in", values, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoNotIn(List<String> values) {
            addCriterion("FROM_FUND_NO not in", values, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoBetween(String value1, String value2) {
            addCriterion("FROM_FUND_NO between", value1, value2, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andFromFundNoNotBetween(String value1, String value2) {
            addCriterion("FROM_FUND_NO not between", value1, value2, "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoIsNull() {
            addCriterion("TO_FUND_NO is null");
            return (Criteria) this;
        }

        public Criteria andToFundNoIsNotNull() {
            addCriterion("TO_FUND_NO is not null");
            return (Criteria) this;
        }

        public Criteria andToFundNoEqualTo(String value) {
            addCriterion("TO_FUND_NO =", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoNotEqualTo(String value) {
            addCriterion("TO_FUND_NO <>", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoGreaterThan(String value) {
            addCriterion("TO_FUND_NO >", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoGreaterThanOrEqualTo(String value) {
            addCriterion("TO_FUND_NO >=", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoLessThan(String value) {
            addCriterion("TO_FUND_NO <", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoLessThanOrEqualTo(String value) {
            addCriterion("TO_FUND_NO <=", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoLike(String value) {
            addCriterion("TO_FUND_NO like", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoNotLike(String value) {
            addCriterion("TO_FUND_NO not like", value, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoIn(List<String> values) {
            addCriterion("TO_FUND_NO in", values, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoNotIn(List<String> values) {
            addCriterion("TO_FUND_NO not in", values, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoBetween(String value1, String value2) {
            addCriterion("TO_FUND_NO between", value1, value2, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoNotBetween(String value1, String value2) {
            addCriterion("TO_FUND_NO not between", value1, value2, "toFundNo");
            return (Criteria) this;
        }

        public Criteria andDcTypeIsNull() {
            addCriterion("DC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDcTypeIsNotNull() {
            addCriterion("DC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDcTypeEqualTo(String value) {
            addCriterion("DC_TYPE =", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotEqualTo(String value) {
            addCriterion("DC_TYPE <>", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeGreaterThan(String value) {
            addCriterion("DC_TYPE >", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DC_TYPE >=", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeLessThan(String value) {
            addCriterion("DC_TYPE <", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeLessThanOrEqualTo(String value) {
            addCriterion("DC_TYPE <=", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeLike(String value) {
            addCriterion("DC_TYPE like", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotLike(String value) {
            addCriterion("DC_TYPE not like", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeIn(List<String> values) {
            addCriterion("DC_TYPE in", values, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotIn(List<String> values) {
            addCriterion("DC_TYPE not in", values, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeBetween(String value1, String value2) {
            addCriterion("DC_TYPE between", value1, value2, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotBetween(String value1, String value2) {
            addCriterion("DC_TYPE not between", value1, value2, "dcType");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andCntIsNull() {
            addCriterion("CNT is null");
            return (Criteria) this;
        }

        public Criteria andCntIsNotNull() {
            addCriterion("CNT is not null");
            return (Criteria) this;
        }

        public Criteria andCntEqualTo(Integer value) {
            addCriterion("CNT =", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotEqualTo(Integer value) {
            addCriterion("CNT <>", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntGreaterThan(Integer value) {
            addCriterion("CNT >", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("CNT >=", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLessThan(Integer value) {
            addCriterion("CNT <", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLessThanOrEqualTo(Integer value) {
            addCriterion("CNT <=", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntIn(List<Integer> values) {
            addCriterion("CNT in", values, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotIn(List<Integer> values) {
            addCriterion("CNT not in", values, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntBetween(Integer value1, Integer value2) {
            addCriterion("CNT between", value1, value2, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotBetween(Integer value1, Integer value2) {
            addCriterion("CNT not between", value1, value2, "cnt");
            return (Criteria) this;
        }

        public Criteria andFlagCancelIsNull() {
            addCriterion("FLAG_CANCEL is null");
            return (Criteria) this;
        }

        public Criteria andFlagCancelIsNotNull() {
            addCriterion("FLAG_CANCEL is not null");
            return (Criteria) this;
        }

        public Criteria andFlagCancelEqualTo(String value) {
            addCriterion("FLAG_CANCEL =", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelNotEqualTo(String value) {
            addCriterion("FLAG_CANCEL <>", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelGreaterThan(String value) {
            addCriterion("FLAG_CANCEL >", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelGreaterThanOrEqualTo(String value) {
            addCriterion("FLAG_CANCEL >=", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelLessThan(String value) {
            addCriterion("FLAG_CANCEL <", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelLessThanOrEqualTo(String value) {
            addCriterion("FLAG_CANCEL <=", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelLike(String value) {
            addCriterion("FLAG_CANCEL like", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelNotLike(String value) {
            addCriterion("FLAG_CANCEL not like", value, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelIn(List<String> values) {
            addCriterion("FLAG_CANCEL in", values, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelNotIn(List<String> values) {
            addCriterion("FLAG_CANCEL not in", values, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelBetween(String value1, String value2) {
            addCriterion("FLAG_CANCEL between", value1, value2, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andFlagCancelNotBetween(String value1, String value2) {
            addCriterion("FLAG_CANCEL not between", value1, value2, "flagCancel");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdIsNull() {
            addCriterion("RELATED_TRANS_ID is null");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdIsNotNull() {
            addCriterion("RELATED_TRANS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdEqualTo(String value) {
            addCriterion("RELATED_TRANS_ID =", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdNotEqualTo(String value) {
            addCriterion("RELATED_TRANS_ID <>", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdGreaterThan(String value) {
            addCriterion("RELATED_TRANS_ID >", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdGreaterThanOrEqualTo(String value) {
            addCriterion("RELATED_TRANS_ID >=", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdLessThan(String value) {
            addCriterion("RELATED_TRANS_ID <", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdLessThanOrEqualTo(String value) {
            addCriterion("RELATED_TRANS_ID <=", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdLike(String value) {
            addCriterion("RELATED_TRANS_ID like", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdNotLike(String value) {
            addCriterion("RELATED_TRANS_ID not like", value, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdIn(List<String> values) {
            addCriterion("RELATED_TRANS_ID in", values, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdNotIn(List<String> values) {
            addCriterion("RELATED_TRANS_ID not in", values, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdBetween(String value1, String value2) {
            addCriterion("RELATED_TRANS_ID between", value1, value2, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdNotBetween(String value1, String value2) {
            addCriterion("RELATED_TRANS_ID not between", value1, value2, "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andActBalAfterIsNull() {
            addCriterion("ACT_BAL_AFTER is null");
            return (Criteria) this;
        }

        public Criteria andActBalAfterIsNotNull() {
            addCriterion("ACT_BAL_AFTER is not null");
            return (Criteria) this;
        }

        public Criteria andActBalAfterEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER =", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterNotEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER <>", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterGreaterThan(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER >", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER >=", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterLessThan(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER <", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER <=", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_AFTER in", values, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterNotIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_AFTER not in", values, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_AFTER between", value1, value2, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_AFTER not between", value1, value2, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeIsNull() {
            addCriterion("ACT_BAL_BEFORE is null");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeIsNotNull() {
            addCriterion("ACT_BAL_BEFORE is not null");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE =", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeNotEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE <>", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeGreaterThan(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE >", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE >=", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeLessThan(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE <", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE <=", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_BEFORE in", values, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeNotIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_BEFORE not in", values, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_BEFORE between", value1, value2, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_BEFORE not between", value1, value2, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andExtId1IsNull() {
            addCriterion("EXT_ID1 is null");
            return (Criteria) this;
        }

        public Criteria andExtId1IsNotNull() {
            addCriterion("EXT_ID1 is not null");
            return (Criteria) this;
        }

        public Criteria andExtId1EqualTo(String value) {
            addCriterion("EXT_ID1 =", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1NotEqualTo(String value) {
            addCriterion("EXT_ID1 <>", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1GreaterThan(String value) {
            addCriterion("EXT_ID1 >", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1GreaterThanOrEqualTo(String value) {
            addCriterion("EXT_ID1 >=", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1LessThan(String value) {
            addCriterion("EXT_ID1 <", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1LessThanOrEqualTo(String value) {
            addCriterion("EXT_ID1 <=", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1Like(String value) {
            addCriterion("EXT_ID1 like", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1NotLike(String value) {
            addCriterion("EXT_ID1 not like", value, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1In(List<String> values) {
            addCriterion("EXT_ID1 in", values, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1NotIn(List<String> values) {
            addCriterion("EXT_ID1 not in", values, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1Between(String value1, String value2) {
            addCriterion("EXT_ID1 between", value1, value2, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId1NotBetween(String value1, String value2) {
            addCriterion("EXT_ID1 not between", value1, value2, "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId2IsNull() {
            addCriterion("EXT_ID2 is null");
            return (Criteria) this;
        }

        public Criteria andExtId2IsNotNull() {
            addCriterion("EXT_ID2 is not null");
            return (Criteria) this;
        }

        public Criteria andExtId2EqualTo(String value) {
            addCriterion("EXT_ID2 =", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2NotEqualTo(String value) {
            addCriterion("EXT_ID2 <>", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2GreaterThan(String value) {
            addCriterion("EXT_ID2 >", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2GreaterThanOrEqualTo(String value) {
            addCriterion("EXT_ID2 >=", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2LessThan(String value) {
            addCriterion("EXT_ID2 <", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2LessThanOrEqualTo(String value) {
            addCriterion("EXT_ID2 <=", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2Like(String value) {
            addCriterion("EXT_ID2 like", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2NotLike(String value) {
            addCriterion("EXT_ID2 not like", value, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2In(List<String> values) {
            addCriterion("EXT_ID2 in", values, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2NotIn(List<String> values) {
            addCriterion("EXT_ID2 not in", values, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2Between(String value1, String value2) {
            addCriterion("EXT_ID2 between", value1, value2, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtId2NotBetween(String value1, String value2) {
            addCriterion("EXT_ID2 not between", value1, value2, "extId2");
            return (Criteria) this;
        }

        public Criteria andExtCommetsIsNull() {
            addCriterion("EXT_COMMETS is null");
            return (Criteria) this;
        }

        public Criteria andExtCommetsIsNotNull() {
            addCriterion("EXT_COMMETS is not null");
            return (Criteria) this;
        }

        public Criteria andExtCommetsEqualTo(String value) {
            addCriterion("EXT_COMMETS =", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsNotEqualTo(String value) {
            addCriterion("EXT_COMMETS <>", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsGreaterThan(String value) {
            addCriterion("EXT_COMMETS >", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsGreaterThanOrEqualTo(String value) {
            addCriterion("EXT_COMMETS >=", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsLessThan(String value) {
            addCriterion("EXT_COMMETS <", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsLessThanOrEqualTo(String value) {
            addCriterion("EXT_COMMETS <=", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsLike(String value) {
            addCriterion("EXT_COMMETS like", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsNotLike(String value) {
            addCriterion("EXT_COMMETS not like", value, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsIn(List<String> values) {
            addCriterion("EXT_COMMETS in", values, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsNotIn(List<String> values) {
            addCriterion("EXT_COMMETS not in", values, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsBetween(String value1, String value2) {
            addCriterion("EXT_COMMETS between", value1, value2, "extCommets");
            return (Criteria) this;
        }

        public Criteria andExtCommetsNotBetween(String value1, String value2) {
            addCriterion("EXT_COMMETS not between", value1, value2, "extCommets");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andLogUuidLikeInsensitive(String value) {
            addCriterion("upper(LOG_UUID) like", value.toUpperCase(), "logUuid");
            return (Criteria) this;
        }

        public Criteria andSettDateLikeInsensitive(String value) {
            addCriterion("upper(SETT_DATE) like", value.toUpperCase(), "settDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLikeInsensitive(String value) {
            addCriterion("upper(CONS_DATE) like", value.toUpperCase(), "consDate");
            return (Criteria) this;
        }

        public Criteria andTxSnoLikeInsensitive(String value) {
            addCriterion("upper(TX_SNO) like", value.toUpperCase(), "txSno");
            return (Criteria) this;
        }

        public Criteria andTransCodeLikeInsensitive(String value) {
            addCriterion("upper(TRANS_CODE) like", value.toUpperCase(), "transCode");
            return (Criteria) this;
        }

        public Criteria andSubTransCodeLikeInsensitive(String value) {
            addCriterion("upper(SUB_TRANS_CODE) like", value.toUpperCase(), "subTransCode");
            return (Criteria) this;
        }

        public Criteria andBizTypeLikeInsensitive(String value) {
            addCriterion("upper(BIZ_TYPE) like", value.toUpperCase(), "bizType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLikeInsensitive(String value) {
            addCriterion("upper(BIZ_DTL_TYPE) like", value.toUpperCase(), "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andFromFundNoLikeInsensitive(String value) {
            addCriterion("upper(FROM_FUND_NO) like", value.toUpperCase(), "fromFundNo");
            return (Criteria) this;
        }

        public Criteria andToFundNoLikeInsensitive(String value) {
            addCriterion("upper(TO_FUND_NO) like", value.toUpperCase(), "toFundNo");
            return (Criteria) this;
        }

        public Criteria andDcTypeLikeInsensitive(String value) {
            addCriterion("upper(DC_TYPE) like", value.toUpperCase(), "dcType");
            return (Criteria) this;
        }

        public Criteria andFlagCancelLikeInsensitive(String value) {
            addCriterion("upper(FLAG_CANCEL) like", value.toUpperCase(), "flagCancel");
            return (Criteria) this;
        }

        public Criteria andRelatedTransIdLikeInsensitive(String value) {
            addCriterion("upper(RELATED_TRANS_ID) like", value.toUpperCase(), "relatedTransId");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andExtId1LikeInsensitive(String value) {
            addCriterion("upper(EXT_ID1) like", value.toUpperCase(), "extId1");
            return (Criteria) this;
        }

        public Criteria andExtId2LikeInsensitive(String value) {
            addCriterion("upper(EXT_ID2) like", value.toUpperCase(), "extId2");
            return (Criteria) this;
        }

        public Criteria andExtCommetsLikeInsensitive(String value) {
            addCriterion("upper(EXT_COMMETS) like", value.toUpperCase(), "extCommets");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 19 22:41:13 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_TRANS_LOGS_HIS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}