package onight.act.ordbgens.act.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="T_ACT_TRANS_LOGS_DEBT")
@AllArgsConstructor
@NoArgsConstructor
public class TActTransLogsDebt extends TActTransLogsDebtKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.FROM_FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String fromFundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.TO_FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String toFundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.FLAG_CANCEL
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String flagCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.RELATED_TRANS_ID
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String relatedTransId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.STATUS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.CREATE_TIME
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_TRANS_LOGS_DEBT.UPDATE_TIME
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.FROM_FUND_NO
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.FROM_FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getFromFundNo() {
        return fromFundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.FROM_FUND_NO
     *
     * @param fromFundNo the value for T_ACT_TRANS_LOGS_DEBT.FROM_FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setFromFundNo(String fromFundNo) {
        this.fromFundNo = fromFundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.TO_FUND_NO
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.TO_FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getToFundNo() {
        return toFundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.TO_FUND_NO
     *
     * @param toFundNo the value for T_ACT_TRANS_LOGS_DEBT.TO_FUND_NO
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setToFundNo(String toFundNo) {
        this.toFundNo = toFundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.FLAG_CANCEL
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.FLAG_CANCEL
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getFlagCancel() {
        return flagCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.FLAG_CANCEL
     *
     * @param flagCancel the value for T_ACT_TRANS_LOGS_DEBT.FLAG_CANCEL
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setFlagCancel(String flagCancel) {
        this.flagCancel = flagCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.RELATED_TRANS_ID
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.RELATED_TRANS_ID
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getRelatedTransId() {
        return relatedTransId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.RELATED_TRANS_ID
     *
     * @param relatedTransId the value for T_ACT_TRANS_LOGS_DEBT.RELATED_TRANS_ID
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setRelatedTransId(String relatedTransId) {
        this.relatedTransId = relatedTransId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.STATUS
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.STATUS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.STATUS
     *
     * @param status the value for T_ACT_TRANS_LOGS_DEBT.STATUS
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.CREATE_TIME
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.CREATE_TIME
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.CREATE_TIME
     *
     * @param createTime the value for T_ACT_TRANS_LOGS_DEBT.CREATE_TIME
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_TRANS_LOGS_DEBT.UPDATE_TIME
     *
     * @return the value of T_ACT_TRANS_LOGS_DEBT.UPDATE_TIME
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_TRANS_LOGS_DEBT.UPDATE_TIME
     *
     * @param updateTime the value for T_ACT_TRANS_LOGS_DEBT.UPDATE_TIME
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_DEBT
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TActTransLogsDebt other = (TActTransLogsDebt) that;
        return (this.getLogUuid() == null ? other.getLogUuid() == null : this.getLogUuid().equals(other.getLogUuid()))
            && (this.getFromFundNo() == null ? other.getFromFundNo() == null : this.getFromFundNo().equals(other.getFromFundNo()))
            && (this.getToFundNo() == null ? other.getToFundNo() == null : this.getToFundNo().equals(other.getToFundNo()))
            && (this.getFlagCancel() == null ? other.getFlagCancel() == null : this.getFlagCancel().equals(other.getFlagCancel()))
            && (this.getRelatedTransId() == null ? other.getRelatedTransId() == null : this.getRelatedTransId().equals(other.getRelatedTransId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_DEBT
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogUuid() == null) ? 0 : getLogUuid().hashCode());
        result = prime * result + ((getFromFundNo() == null) ? 0 : getFromFundNo().hashCode());
        result = prime * result + ((getToFundNo() == null) ? 0 : getToFundNo().hashCode());
        result = prime * result + ((getFlagCancel() == null) ? 0 : getFlagCancel().hashCode());
        result = prime * result + ((getRelatedTransId() == null) ? 0 : getRelatedTransId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRANS_LOGS_DEBT
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fromFundNo=").append(fromFundNo);
        sb.append(", toFundNo=").append(toFundNo);
        sb.append(", flagCancel=").append(flagCancel);
        sb.append(", relatedTransId=").append(relatedTransId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}