
USE TFG;

DROP TABLE IF EXISTS TFG_USER_ID_LIST;
CREATE TABLE TFG_USER_ID_LIST (
  USER_ID bigint(20) NOT NULL ,
  STATUS int(2) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='用户ID列表';


create index TFG_USER_ID_LIST_IDX0 on TFG_USER_ID_LIST
(
   STATUS
);

DROP TABLE IF EXISTS TFG_LOGIN_USER;
CREATE TABLE TFG_LOGIN_USER (
  USER_NAME varchar(32) NOT NULL, 
  LOGIN_ID varchar(32) DEFAULT NULL,
  NICKNAME varchar(32) DEFAULT NULL,
  EMAIL varchar(64) DEFAULT NULL,
  MOBILE varchar(20) DEFAULT NULL,

  THIRD_LOGINID1 varchar(64) DEFAULT NULL,
  THIRD_LOGINID2 varchar(32) DEFAULT NULL,
  
  TRADE_NO varchar(64) DEFAULT NULL,

  BC_ADDRESS varchar(64) DEFAULT NULL,
  BC_PKI	 varchar(256) DEFAULT NULL ,
  BC_METADATA varchar(1024) DEFAULT NULL ,
  

  REG_TYPE varchar(32) COMMENT '注册类型',
  STATUS int(2) DEFAULT NULL,
  PASSWORD varchar(32) DEFAULT NULL COMMENT 'md5加密处理',
  TRADE_PASSWORD varchar(32) DEFAULT NULL COMMENT '交易密码',
  UPDATE_TIME datetime DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  
  LAST_LOGIN_TIME datetime DEFAULT NULL COMMENT '最后一次登录时间',
  LAST_LOGIN_IP varchar(20) DEFAULT NULL COMMENT '最后一次登录时的用户ip',
  LAST_LOGIN_TERMINAL int(2) DEFAULT '0' COMMENT '最后登录终端， 1:browser 2:android  3:ios',
  LAST_LOGIN_SYSINFO varchar(40) DEFAULT '' COMMENT '最后登录终端的系统信息， 如：iphone6 4G',
    
  PRIMARY KEY (USER_NAME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='用户登录表';

create index TFG_LOGIN_USER_IDX1 on TFG_LOGIN_USER
(
   USER_NAME
);

create index TFG_LOGIN_USER_IDX2 on TFG_LOGIN_USER
(
   THIRD_LOGINID1
);


create index TFG_LOGIN_USER_IDX3 on TFG_LOGIN_USER
(
   BC_ADDRESS
);

create index TFG_LOGIN_USER_IDX4 on TFG_LOGIN_USER
(
   EMAIL
);
create index TFG_LOGIN_USER_IDX5 on TFG_LOGIN_USER
(
   MOBILE
);
create unique index TFG_LOGIN_USER_IDX6 on TFG_LOGIN_USER
(
   TRADE_NO
);



DROP TABLE IF EXISTS TFG_USER_INFO;
CREATE TABLE TFG_USER_INFO (
  USER_ID bigint(20) NOT NULL ,
  NICKNAME varchar(32) DEFAULT NULL,
  PARENT_ID bigint(20) NOT NULL  COMMENT '上级ID', 
  RECOMMEND_ID	bigint(20) NOT NULL  COMMENT '推荐人',
  USER_TYPE varchar(20) DEFAULT NULL COMMENT '用户类型',

  SECURITY_EMAIL varchar(64) DEFAULT NULL COMMENT '密码找回邮箱',
  REAL_NAME varchar(50) DEFAULT NULL COMMENT '姓名',
  STATUS int(2) DEFAULT NULL,
  ID_NO varchar(20) DEFAULT NULL COMMENT '身份证号',
  UPDATE_TIME datetime DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,

  QQ_ID varchar(32) DEFAULT NULL,
  WECHAT_ID varchar(32) DEFAULT NULL,
  MOBILE varchar(20) DEFAULT NULL,
  EMAIL varchar(64) DEFAULT NULL,
  RENREN varchar(20) DEFAULT NULL,
  WEIBO varchar(20) DEFAULT NULL,

  FACE int(4) DEFAULT NULL COMMENT '0 用户上传, >= 10 预定义头像',
  FACE_URL varchar(255) DEFAULT NULL COMMENT '子定义头像存放url地址',
  GENDER int(2) DEFAULT NULL COMMENT '0:未选择，1:男，2:女',
  BIRTHDAY date DEFAULT NULL COMMENT '生日',
  COUNTRY varchar(100) DEFAULT NULL COMMENT '国籍',
  PROVINCE varchar(16) DEFAULT '' COMMENT '所省份',
  CITY varchar(16) DEFAULT '' COMMENT '所属市',
  HOME_ADDRESS varchar(64) DEFAULT '' COMMENT '家庭地址',
  WORK_ADDRESS varchar(100) DEFAULT NULL COMMENT '工作地址',

  MOBILE1 varchar(20) DEFAULT NULL,

  MOBILE2 varchar(20) DEFAULT NULL,
  MOBILE3 varchar(20) DEFAULT NULL ,
  MOBILEHIS varchar(256) DEFAULT NULL COMMENT '联系号码历史' ,
 REMARK varchar(255) DEFAULT NULL COMMENT '备注',

  REG_TIME datetime DEFAULT NULL COMMENT '注册时间',
  REG_IP varchar(20) DEFAULT NULL COMMENT '注册时用户IP',

  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='用户基本信息表';

create index IDX_TFG_USER_INFO_PARENTID on TFG_USER_INFO
(
   PARENT_ID
);


-- 角色

DROP TABLE IF EXISTS TFG_ROLE;
CREATE TABLE TFG_ROLE (
  ROLE_ID VARCHAR(36) NOT NULL ,
  PARENT_ROLE_ID VARCHAR(36) NOT NULL ,
  ROLE_NAME VARCHAR(64) DEFAULT NULL,
  ROLE_DESC VARCHAR(512) DEFAULT NULL,
  STATUS VARCHAR(4) DEFAULT NULL,
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表';


DROP TABLE IF EXISTS TFG_USER_ROLE;
CREATE TABLE TFG_USER_ROLE (
  USER_ROLE_ID VARCHAR(36) NOT NULL ,
  USER_ID VARCHAR(36) DEFAULT NULL,
  ROLE_ID VARCHAR(36) DEFAULT NULL,
  STATUS VARCHAR(4) DEFAULT NULL,
  PRIMARY KEY (USER_ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户与角色';


-- 组

DROP TABLE IF EXISTS TFG_GROUP;
CREATE TABLE TFG_GROUP (
  GROUP_ID VARCHAR(36) NOT NULL ,
  PARENT_GROUP_ID VARCHAR(36) NOT NULL ,
  GROUP_NAME VARCHAR(64) DEFAULT NULL,
  GROUP_DESC VARCHAR(512) DEFAULT NULL,
  STATUS VARCHAR(4) DEFAULT NULL,
  PRIMARY KEY (GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='组表';



DROP TABLE IF EXISTS TFG_USER_GROUP;
CREATE TABLE TFG_USER_GROUP (
  USER_GROUP_ID VARCHAR(20) NOT NULL ,
  USER_ID VARCHAR(20) DEFAULT NULL,
  GROUP_ID VARCHAR(20) DEFAULT NULL,
  STATUS VARCHAR(4) DEFAULT NULL,
  PRIMARY KEY (USER_GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户与组';





