package onight.act.ordbgens.act.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class TActInterestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public TActInterestExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInstLogidIsNull() {
            addCriterion("INST_LOGID is null");
            return (Criteria) this;
        }

        public Criteria andInstLogidIsNotNull() {
            addCriterion("INST_LOGID is not null");
            return (Criteria) this;
        }

        public Criteria andInstLogidEqualTo(String value) {
            addCriterion("INST_LOGID =", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidNotEqualTo(String value) {
            addCriterion("INST_LOGID <>", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidGreaterThan(String value) {
            addCriterion("INST_LOGID >", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidGreaterThanOrEqualTo(String value) {
            addCriterion("INST_LOGID >=", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidLessThan(String value) {
            addCriterion("INST_LOGID <", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidLessThanOrEqualTo(String value) {
            addCriterion("INST_LOGID <=", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidLike(String value) {
            addCriterion("INST_LOGID like", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidNotLike(String value) {
            addCriterion("INST_LOGID not like", value, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidIn(List<String> values) {
            addCriterion("INST_LOGID in", values, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidNotIn(List<String> values) {
            addCriterion("INST_LOGID not in", values, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidBetween(String value1, String value2) {
            addCriterion("INST_LOGID between", value1, value2, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInstLogidNotBetween(String value1, String value2) {
            addCriterion("INST_LOGID not between", value1, value2, "instLogid");
            return (Criteria) this;
        }

        public Criteria andInterestDateIsNull() {
            addCriterion("INTEREST_DATE is null");
            return (Criteria) this;
        }

        public Criteria andInterestDateIsNotNull() {
            addCriterion("INTEREST_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andInterestDateEqualTo(String value) {
            addCriterion("INTEREST_DATE =", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateNotEqualTo(String value) {
            addCriterion("INTEREST_DATE <>", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateGreaterThan(String value) {
            addCriterion("INTEREST_DATE >", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateGreaterThanOrEqualTo(String value) {
            addCriterion("INTEREST_DATE >=", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateLessThan(String value) {
            addCriterion("INTEREST_DATE <", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateLessThanOrEqualTo(String value) {
            addCriterion("INTEREST_DATE <=", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateLike(String value) {
            addCriterion("INTEREST_DATE like", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateNotLike(String value) {
            addCriterion("INTEREST_DATE not like", value, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateIn(List<String> values) {
            addCriterion("INTEREST_DATE in", values, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateNotIn(List<String> values) {
            addCriterion("INTEREST_DATE not in", values, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateBetween(String value1, String value2) {
            addCriterion("INTEREST_DATE between", value1, value2, "interestDate");
            return (Criteria) this;
        }

        public Criteria andInterestDateNotBetween(String value1, String value2) {
            addCriterion("INTEREST_DATE not between", value1, value2, "interestDate");
            return (Criteria) this;
        }

        public Criteria andFundNoIsNull() {
            addCriterion("FUND_NO is null");
            return (Criteria) this;
        }

        public Criteria andFundNoIsNotNull() {
            addCriterion("FUND_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFundNoEqualTo(String value) {
            addCriterion("FUND_NO =", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoNotEqualTo(String value) {
            addCriterion("FUND_NO <>", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoGreaterThan(String value) {
            addCriterion("FUND_NO >", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_NO >=", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoLessThan(String value) {
            addCriterion("FUND_NO <", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoLessThanOrEqualTo(String value) {
            addCriterion("FUND_NO <=", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoLike(String value) {
            addCriterion("FUND_NO like", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoNotLike(String value) {
            addCriterion("FUND_NO not like", value, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoIn(List<String> values) {
            addCriterion("FUND_NO in", values, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoNotIn(List<String> values) {
            addCriterion("FUND_NO not in", values, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoBetween(String value1, String value2) {
            addCriterion("FUND_NO between", value1, value2, "fundNo");
            return (Criteria) this;
        }

        public Criteria andFundNoNotBetween(String value1, String value2) {
            addCriterion("FUND_NO not between", value1, value2, "fundNo");
            return (Criteria) this;
        }

        public Criteria andActNoIsNull() {
            addCriterion("ACT_NO is null");
            return (Criteria) this;
        }

        public Criteria andActNoIsNotNull() {
            addCriterion("ACT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andActNoEqualTo(String value) {
            addCriterion("ACT_NO =", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotEqualTo(String value) {
            addCriterion("ACT_NO <>", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThan(String value) {
            addCriterion("ACT_NO >", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_NO >=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThan(String value) {
            addCriterion("ACT_NO <", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThanOrEqualTo(String value) {
            addCriterion("ACT_NO <=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLike(String value) {
            addCriterion("ACT_NO like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotLike(String value) {
            addCriterion("ACT_NO not like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoIn(List<String> values) {
            addCriterion("ACT_NO in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotIn(List<String> values) {
            addCriterion("ACT_NO not in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoBetween(String value1, String value2) {
            addCriterion("ACT_NO between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotBetween(String value1, String value2) {
            addCriterion("ACT_NO not between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andInterestTypeIsNull() {
            addCriterion("INTEREST_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andInterestTypeIsNotNull() {
            addCriterion("INTEREST_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andInterestTypeEqualTo(String value) {
            addCriterion("INTEREST_TYPE =", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotEqualTo(String value) {
            addCriterion("INTEREST_TYPE <>", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeGreaterThan(String value) {
            addCriterion("INTEREST_TYPE >", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeGreaterThanOrEqualTo(String value) {
            addCriterion("INTEREST_TYPE >=", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLessThan(String value) {
            addCriterion("INTEREST_TYPE <", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLessThanOrEqualTo(String value) {
            addCriterion("INTEREST_TYPE <=", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLike(String value) {
            addCriterion("INTEREST_TYPE like", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotLike(String value) {
            addCriterion("INTEREST_TYPE not like", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeIn(List<String> values) {
            addCriterion("INTEREST_TYPE in", values, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotIn(List<String> values) {
            addCriterion("INTEREST_TYPE not in", values, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeBetween(String value1, String value2) {
            addCriterion("INTEREST_TYPE between", value1, value2, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotBetween(String value1, String value2) {
            addCriterion("INTEREST_TYPE not between", value1, value2, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestAmountIsNull() {
            addCriterion("INTEREST_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andInterestAmountIsNotNull() {
            addCriterion("INTEREST_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andInterestAmountEqualTo(BigDecimal value) {
            addCriterion("INTEREST_AMOUNT =", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountNotEqualTo(BigDecimal value) {
            addCriterion("INTEREST_AMOUNT <>", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountGreaterThan(BigDecimal value) {
            addCriterion("INTEREST_AMOUNT >", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST_AMOUNT >=", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountLessThan(BigDecimal value) {
            addCriterion("INTEREST_AMOUNT <", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST_AMOUNT <=", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountIn(List<BigDecimal> values) {
            addCriterion("INTEREST_AMOUNT in", values, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountNotIn(List<BigDecimal> values) {
            addCriterion("INTEREST_AMOUNT not in", values, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST_AMOUNT between", value1, value2, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST_AMOUNT not between", value1, value2, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNull() {
            addCriterion("GMT_MODIFY is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNotNull() {
            addCriterion("GMT_MODIFY is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyEqualTo(Date value) {
            addCriterion("GMT_MODIFY =", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotEqualTo(Date value) {
            addCriterion("GMT_MODIFY <>", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThan(Date value) {
            addCriterion("GMT_MODIFY >", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFY >=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThan(Date value) {
            addCriterion("GMT_MODIFY <", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFY <=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIn(List<Date> values) {
            addCriterion("GMT_MODIFY in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotIn(List<Date> values) {
            addCriterion("GMT_MODIFY not in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFY between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFY not between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNull() {
            addCriterion("TRADE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNotNull() {
            addCriterion("TRADE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDateEqualTo(String value) {
            addCriterion("TRADE_DATE =", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotEqualTo(String value) {
            addCriterion("TRADE_DATE <>", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThan(String value) {
            addCriterion("TRADE_DATE >", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_DATE >=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThan(String value) {
            addCriterion("TRADE_DATE <", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThanOrEqualTo(String value) {
            addCriterion("TRADE_DATE <=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLike(String value) {
            addCriterion("TRADE_DATE like", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotLike(String value) {
            addCriterion("TRADE_DATE not like", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIn(List<String> values) {
            addCriterion("TRADE_DATE in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotIn(List<String> values) {
            addCriterion("TRADE_DATE not in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateBetween(String value1, String value2) {
            addCriterion("TRADE_DATE between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotBetween(String value1, String value2) {
            addCriterion("TRADE_DATE not between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andRateValueIsNull() {
            addCriterion("RATE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andRateValueIsNotNull() {
            addCriterion("RATE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andRateValueEqualTo(BigDecimal value) {
            addCriterion("RATE_VALUE =", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueNotEqualTo(BigDecimal value) {
            addCriterion("RATE_VALUE <>", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueGreaterThan(BigDecimal value) {
            addCriterion("RATE_VALUE >", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RATE_VALUE >=", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueLessThan(BigDecimal value) {
            addCriterion("RATE_VALUE <", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RATE_VALUE <=", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueIn(List<BigDecimal> values) {
            addCriterion("RATE_VALUE in", values, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueNotIn(List<BigDecimal> values) {
            addCriterion("RATE_VALUE not in", values, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RATE_VALUE between", value1, value2, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RATE_VALUE not between", value1, value2, "rateValue");
            return (Criteria) this;
        }

        public Criteria andUnitNoIsNull() {
            addCriterion("UNIT_NO is null");
            return (Criteria) this;
        }

        public Criteria andUnitNoIsNotNull() {
            addCriterion("UNIT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andUnitNoEqualTo(String value) {
            addCriterion("UNIT_NO =", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoNotEqualTo(String value) {
            addCriterion("UNIT_NO <>", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoGreaterThan(String value) {
            addCriterion("UNIT_NO >", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT_NO >=", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoLessThan(String value) {
            addCriterion("UNIT_NO <", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoLessThanOrEqualTo(String value) {
            addCriterion("UNIT_NO <=", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoLike(String value) {
            addCriterion("UNIT_NO like", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoNotLike(String value) {
            addCriterion("UNIT_NO not like", value, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoIn(List<String> values) {
            addCriterion("UNIT_NO in", values, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoNotIn(List<String> values) {
            addCriterion("UNIT_NO not in", values, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoBetween(String value1, String value2) {
            addCriterion("UNIT_NO between", value1, value2, "unitNo");
            return (Criteria) this;
        }

        public Criteria andUnitNoNotBetween(String value1, String value2) {
            addCriterion("UNIT_NO not between", value1, value2, "unitNo");
            return (Criteria) this;
        }

        public Criteria andInstLogidLikeInsensitive(String value) {
            addCriterion("upper(INST_LOGID) like", value.toUpperCase(), "instLogid");
            return (Criteria) this;
        }

        public Criteria andInterestDateLikeInsensitive(String value) {
            addCriterion("upper(INTEREST_DATE) like", value.toUpperCase(), "interestDate");
            return (Criteria) this;
        }

        public Criteria andFundNoLikeInsensitive(String value) {
            addCriterion("upper(FUND_NO) like", value.toUpperCase(), "fundNo");
            return (Criteria) this;
        }

        public Criteria andActNoLikeInsensitive(String value) {
            addCriterion("upper(ACT_NO) like", value.toUpperCase(), "actNo");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLikeInsensitive(String value) {
            addCriterion("upper(INTEREST_TYPE) like", value.toUpperCase(), "interestType");
            return (Criteria) this;
        }

        public Criteria andTradeDateLikeInsensitive(String value) {
            addCriterion("upper(TRADE_DATE) like", value.toUpperCase(), "tradeDate");
            return (Criteria) this;
        }

        public Criteria andUnitNoLikeInsensitive(String value) {
            addCriterion("upper(UNIT_NO) like", value.toUpperCase(), "unitNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 19 22:41:13 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_INTEREST
     *
     * @mbggenerated Tue Jan 19 22:41:13 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}